http:
  port: 7070
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api-ms-tariff-comparison-product-create:
    host: '*'
    paths: '/product/create'
    methods: [ 'POST' ]
  api-ms-tariff-comparison-product-update:
    host: '*'
    paths: '/product/update/id/*'
    methods: [ 'PUT' ]
  api-ms-tariff-comparison-product-delete:
    host: '*'
    paths: '/product/delete/id/*'
    methods: [ 'DELETE' ]
  api-ms-tariff-comparison-product-listall:
    host: '*'
    paths: '/product/listall'
    methods: [ 'GET' ]

  api-ms-tariff-comparison-costs-listall:
    host: '*'
    paths: '/costs/calculation/listall'
    methods: [ 'GET' ]
  api-ms-tariff-comparison-costs-startprocess:
    host: '*'
    paths: '/costs/process/start'
    methods: [ 'GET' ]
  api-ms-tariff-comparison-costs-calculate:
    host: '*'
    paths: '/costs/calculate'
    methods: [ 'POST' ]
  api-ms-tariff-comparison-costs-upload:
    host: '*'
    paths: '/costs/upload'
    methods: [ 'POST' ]
  api-ms-tariff-comparison-costs-file-toprocess-listall:
    host: '*'
    paths: '/costs/file/toprocess/listall'
    methods: [ 'GET' ]
  api-ms-tariff-comparison-costs-calculate-delete:
    host: '*'
    paths: '/costs/delete'
    methods: [ 'DELETE' ]
  api-ms-tariff-comparison-costs-file-toprocess-delete:
    host: '*'
    paths: '/costs/file/toprocess/delete'
    methods: [ 'DELETE' ]

  api-ms-user-get-account:
    host: '*'
    paths: '/account/client/*/me/*'
    methods: [ 'GET' ]
  api-ms-user-create-account:
    host: '*'
    paths: '/account'
    methods: [ 'POST' ]


serviceEndpoints:
  ms-tariff-comparison:
    url: 'http://localhost:3000/ms-tariff-comparison'
  ms-user:
    url: 'http://localhost:3001/ms-user'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
  - keycloak-protect

pipelines:
  ms-tariff-comparison-pipeline:
    apiEndpoints:
      - api-ms-tariff-comparison-product-create
      - api-ms-tariff-comparison-product-update
      - api-ms-tariff-comparison-product-delete
      - api-ms-tariff-comparison-product-listall
      - api-ms-tariff-comparison-costs-listall
      - api-ms-tariff-comparison-costs-startprocess
      - api-ms-tariff-comparison-costs-calculate
      - api-ms-tariff-comparison-costs-upload
      - api-ms-tariff-comparison-costs-file-toprocess-listall
      - api-ms-tariff-comparison-costs-calculate-delete
      - api-ms-tariff-comparison-costs-file-toprocess-delete
    policies:
      - keycloak-protect:
        - action:
            role: Write
      - proxy:
        - action:
            serviceEndpoint: ms-tariff-comparison

  ms-user:
    apiEndpoints:
      - api-ms-user-get-account
      - api-ms-user-create-account
    policies:
      - keycloak-protect:
        - action:
            role: Write
      - proxy:
        - action:
            serviceEndpoint: ms-user