http:
  port: 7070
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api-ms-tariff-comparison-products-create:
    host: '*'
    paths: '/products'
    methods: [ 'POST' ]
  api-ms-tariff-comparison-products-update:
    host: '*'
    paths: '/products/*'
    methods: [ 'PUT' ]
  api-ms-tariff-comparison-products-delete:
    host: '*'
    paths: '/products/*'
    methods: [ 'DELETE' ]
  api-ms-tariff-comparison-products-listall:
    host: '*'
    paths: '/products'
    methods: [ 'GET' ]

  api-ms-tariff-comparison-calculations-listall:
    host: '*'
    paths: '/calculations'
    methods: [ 'GET' ]
  api-ms-tariff-comparison-calculations-calculate:
    host: '*'
    paths: '/calculations/kwhyear/*'
    methods: [ 'GET' ]
  api-ms-tariff-comparison-calculations-calculate-delete:
    host: '*'
    paths: '/calculations'
    methods: [ 'DELETE' ]

  api-ms-tariff-comparison-files-startprocess:
    host: '*'
    paths: '/files/process/starts'
    methods: [ 'POST' ]
  api-ms-tariff-comparison-files-upload:
    host: '*'
    paths: '/files'
    methods: [ 'POST' ]
  api-ms-tariff-comparison-files-listall:
    host: '*'
    paths: '/files'
    methods: [ 'GET' ]
  api-ms-tariff-comparison-files-delete:
    host: '*'
    paths: '/files'
    methods: [ 'DELETE' ]

  api-ms-user-get-account:
    host: '*'
    paths: '/accounts/client/*/id/*'
    methods: [ 'GET' ]
  api-ms-user-create-account:
    host: '*'
    paths: '/accounts'
    methods: [ 'POST' ]


serviceEndpoints:
  ms-tariff-comparison:
    url: 'http://localhost:3000/ms-tariff-comparison'
  ms-user:
    url: 'http://localhost:3001/ms-user'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
  - keycloak-protect

pipelines:
  ms-tariff-comparison-pipeline:
    apiEndpoints:
      - api-ms-tariff-comparison-products-create
      - api-ms-tariff-comparison-products-update
      - api-ms-tariff-comparison-products-delete
      - api-ms-tariff-comparison-products-listall
      - api-ms-tariff-comparison-calculations-listall
      - api-ms-tariff-comparison-calculations-calculate
      - api-ms-tariff-comparison-calculations-calculate-delete
      - api-ms-tariff-comparison-files-startprocess
      - api-ms-tariff-comparison-files-upload
      - api-ms-tariff-comparison-files-listall
      - api-ms-tariff-comparison-files-delete
    policies:
      - keycloak-protect:
        - action:
            role: Write
      - proxy:
        - action:
            serviceEndpoint: ms-tariff-comparison

  ms-user:
    apiEndpoints:
      - api-ms-user-get-account
      - api-ms-user-create-account
    policies:
      - keycloak-protect:
        - action:
            role: Write
      - proxy:
        - action:
            serviceEndpoint: ms-user